SOURCES=sirbonville.o core.o gui.o
CFLAGS=`pkg-config gtk+-2.0 --cflags`
LIBS=`pkg-config gtk+-2.0 --libs`
BINARY=sirbonville.exe


all: $(SOURCES)


link:
	i486-mingw32-gcc $(SOURCES) $(LIBS) -o sirbonville


.c.o:
	i486-mingw32-gcc -c $< -o $@ $(CFLAGS)



